version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: gameuser
      POSTGRES_PASSWORD: gamepass
      POSTGRES_DB: cardgame
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./server
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    env_file:
      - .env

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
